# Generated by Django 5.0.4 on 2024-04-17 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_categoria_options_rename_nome_categoria_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('nome',), 'verbose_name_plural': 'Categorias'},
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='name',
            new_name='nome',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
